name: WillABill
channels:
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  - pip
  
  # Data Science & Analysis
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  
  # Machine Learning & AI
  - xgboost
  - transformers
  - datasets
  - shap
  - numba
  
  # Natural Language Processing
  - spacy
  
  # Statistical Analysis & Modeling
  - salib
  - pygam
  - interpret
  
  # Development Tools
  - jupyterlab
  - debugpy
  
  # Data Processing
  - openpyxl
  - pyarrow
  - pandera
  
  # Web & API
  - requests
  - flask
  - aiohttp
  - httpx
  - dash
  
  # Command Line Tools
  - typer
  - rich
  
  # Utility Libraries
  - pyyaml
  - tqdm
  - click
  - joblib
  - colorama
  - pydantic
  - sqlalchemy
  - psutil
  - fsspec
  - filelock
  
  # Other packages
  - beautifulsoup4
  - jinja2
  - regex
  - packaging
  - pillow
  - typing-extensions
  - progressbar2
  - retrying
  - smart-open
  - ujson
  
  # pip dependencies
  - pip:
    - claude-code-sdk==0.0.23
    - cssselect==1.3.0
    - distro==1.9.0
    - feedfinder2==0.0.4
    - feedparser==6.0.12
    - html5lib==1.1
    - httpx-sse==0.4.1
    - jieba3k==0.35.1
    - jiter==0.11.0
    - lxml==6.0.2
    - mcp==1.14.1
    - newspaper3k==0.2.8
    - nltk==3.9.1
    - oauthlib==3.3.1
    - openai==1.109.1
    - polars==1.33.1
    - pydantic-settings==2.11.0
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - pytrends==4.9.2
    - requests-file==2.1.0
    - requests-oauthlib==2.0.0
    - sgmllib3k==1.0.0
    - sse-starlette==3.0.2
    - starlette==0.48.0
    - tinysegmenter==0.3
    - tldextract==5.3.0
    - tweepy==4.16.0
    - uvicorn==0.37.0